// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLCxXLPwjdu92cs7vaUtgw_GlM1odDGc',
    appId: '1:166997531612:web:0c69844e424ac538becd19',
    messagingSenderId: '166997531612',
    projectId: 'flutter-varios-c8193',
    authDomain: 'flutter-varios-c8193.firebaseapp.com',
    databaseURL: 'https://flutter-varios-c8193-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-c8193.appspot.com',
    measurementId: 'G-CPE9BZCWFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDchH1Ig_PSJluHMe8aeW19suXZmB6bRNY',
    appId: '1:166997531612:android:8b0df562cc6be4e7becd19',
    messagingSenderId: '166997531612',
    projectId: 'flutter-varios-c8193',
    databaseURL: 'https://flutter-varios-c8193-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-c8193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGP7VhIM3k6yrkKQFKS2VHBfevERMGp4',
    appId: '1:166997531612:ios:d5c45e4c02bbd808becd19',
    messagingSenderId: '166997531612',
    projectId: 'flutter-varios-c8193',
    databaseURL: 'https://flutter-varios-c8193-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-c8193.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYGP7VhIM3k6yrkKQFKS2VHBfevERMGp4',
    appId: '1:166997531612:ios:d30d2e9183e4b3f5becd19',
    messagingSenderId: '166997531612',
    projectId: 'flutter-varios-c8193',
    databaseURL: 'https://flutter-varios-c8193-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-c8193.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
